name: build

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
      - name: Check output
        run: ls -la target/release
      - name: Archive release
        run: tar -zcvf release.tar.gz --exclude=target/release/build --exclude=target/release/deps --exclude=target/release/examples --exclude=target/release/incremental --exclude=target/release/.fingerprint target/release
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Release
          path: release.tar.gz
